name: A workflow for my Hello World file
on:
  repository_dispatch:
    types: [build]
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # MY_NAME: "${{ github.event.author.name }}"
          repository: "${{ github.repository}}"
      - name: Echo string
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Gopal"
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
