name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
            MY_NAME: "Gopal"
      - name: Echo string
        run: echo "Hello World"
        shell: bash
           
